
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jxd.mp.model

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lk
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



server:
  port: 8087
